package cgi

var Envs = []string {
	"HTTP_HOST=127.0.0.1",
	"CONTEXT_DOCUMENT_ROOT=/var/www/cgi-bin/",
	"HTTP_USER_AGENT=Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0",
	"SERVER_ADMIN=webmaster@localhost",
	"CONTEXT_PREFIX=/cgi-bin/",
	"SERVER_PORT=80",
	"SERVER_NAME=127.0.0.1",
	"QUERY_STRING=view=home&op=translate&sl=zh-CN&tl=en&text=hello",
	"SCRIPT_FILENAME=/home/raojinlin/app/cgi-bin/index.sh",
	"PWD=/home/raojinlin/app/cgi-bin",
	"HTTP_ACCEPT=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
	"REQUEST_METHOD=GET",
	"SERVER_SIGNATURE=<address>Apache/2.4.29 (Ubuntu) Server at 127.0.0.1 Port 80<address>",
	"SCRIPT_NAME=/cgi-bin/index.sh",
	"HTTP_CONNECTION=keep-alive",
	"REMOTE_PORT=59574",
	"DOCUMENT_ROOT=/var/www/html/",
	"SHLVL=1",
	"SERVER_PROTOCOL=HTTP/1.1",
	"HTTP_COOKIE=session_id=195330b7c8a88be91d838c880a4ee25e",
	"REQUEST_URI=/sayHello",
	"HTTP_ACCEPT_LANGUAGE=en-GB,en;q=0.5",
	"HTTP_UPGRADE_INSECURE_REQUESTS=1",
	"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
	"SERVER_ADDR=127.0.0.1",
	"GATEWAY_INTERFACE=CGI/1.1",
	"HTTP_ACCEPT_ENCODING=gzip, deflate",
	"REQUEST_SCHEME=http",
	"REMOTE_ADDR=127.0.0.1",
	"SERVER_SOFTWARE=Apache/2.4.29 (Ubuntu)",
	"_=/usr/bin/env",
}
